apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-app
  namespace: hello-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-app   # Deployment가 관리할 파드를 찾는 라벨,Deployment 자신을 위한 매칭입니다
  template:
    metadata:
      labels:
        app: hello-app   # 실제로 파드에 붙는 라벨 ★ 이게 핵심
    spec:
      containers:
      - name: hello-app
        # Kustomize가 이 이미지 태그를 관리
        # 본인의 도커 허브 사용자 이름으로 변경
        image: 1jocker1/hello-app:latest
        ports:
        - containerPort: 8080

        
    