apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomization이 관리할 리소스 목록을 정의
resources:
- hello-app-namespace.yaml
- hello-app-deployment.yaml
- hello-app-service.yaml
images:
# 원본 Deployment 파일은 안 건드리고
# 본인의 도커 허브 사용자 이름으로 변경
- name: 1jocker1/hello-app  # 이 이미지를 찾아서
  newName: 1jocker1/hello-app  # 이 이름으로 바꾸고
  newTag: 9addc5b # 이 태그로 바꿔치기