apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Kustomization이 관리할 리소스 목록을 정의
resources:
- hello-app-namespace.yaml
- hello-app-deployment.yaml
- hello-app-service.yaml
# 원본 Deployment 파일은 안 건드리고
# 본인의 도커 허브 사용자 이름으로 변경
images:
- name: 1jocker1/hello-app
  newName: 1jocker1/hello-app
  newTag: c09e9d3
